[package]
name = "openmark"
version = "0.1.0"
edition = "2023_11"
cairo-version = "2.8.0"
scarb-version = "2.8.0"
sierra-version = "2.2.0"
authors = ["Grindy Technologies <hello@grindy.io>"]
description = "OpenMark Contracts written in Cairo for StarkNet, a decentralized ZK Rollup"
documentation = ""
readme = "README.md"
repository = "https://github.com/grindytech/openmark-cairo-contracts"
license-file = "LICENSE"
keywords = ["openmark", "starknet", "cairo", "contracts"]

[dependencies]
starknet = "2.8.0"
openzeppelin = { path = "../cairo-contracts" }
# openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.16.0" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.30.0" }

[scripts]
test = "snforge test"

[[target.starknet-contract]]
sierra = true
casm = false

[tool.fmt]
sort-module-level-items = true
