use snforge_std::EventSpyAssertionsTrait;
use openzeppelin::utils::serde::SerializedAppend;
use openzeppelin::token::erc20::interface::{IERC20Dispatcher, IERC20DispatcherTrait};
use openzeppelin::token::erc1155::interface::{IERC1155Dispatcher, IERC1155DispatcherTrait};
use openzeppelin::access::accesscontrol::interface::{
    IAccessControlDispatcher, IAccessControlDispatcherTrait,
};
use openzeppelin::access::ownable::interface::{IOwnableDispatcher, IOwnableDispatcherTrait};

use snforge_std::{
    declare, ContractClassTrait, start_cheat_caller_address, stop_cheat_caller_address,
    start_cheat_block_timestamp, DeclareResultTrait, get_class_hash, spy_events,
};
use starknet::{ContractAddress};
use openmark::tests::unit::common::{
    SELLER1, SELLER2, BUYER1, BUYER2, TEST_PAYMENT, TEST_NFT, toAddress, setup_balance_at,
    do_setup_oerc721_at, create_stage, create_oerc1155, create_erc20, setup_account, create_oerc721,
    ZERO,
};
use openmark::primitives::types::{Stage, StageType};
use openmark::primitives::constants::{MINTER_ROLE, PERMYRIAD};
use openmark::launchpad::interface::{
    IOStageDispatcher, IOStageDispatcherTrait, IStageBatchSelectorDispatcher,
    IStageBatchSelectorDispatcherTrait,
};
use openmark::assets::interface::{IERC721MinterDispatcher, IERC721MinterDispatcherTrait};
use openmark::launchpad::stage::StageComponent;
use openmark::factory::stage_factory::{StageFactory,};
use openmark::launchpad::events::{TokensBought, StageClosed, SalesWithdrawn};
use openmark::launchpad::stage_batch_selector::StageBatchSelector;
use openmark::factory::interface::{IStageFactoryDispatcher,IStageFactoryDispatcherTrait};
use openmark::factory::stage_factory::StageFactory::StageCreated;

fn create_open_launchpad(
    owner: ContractAddress, commission: u32,
) -> (ContractAddress, IStageFactoryDispatcher) {
    let selector = create_stage(
        StageType::BatchSelector, owner, ZERO(), ZERO(), Option::None, [].span(), commission, owner,
    );
    let batchSelector = create_stage(
        StageType::BatchSelector, owner, ZERO(), ZERO(), Option::None, [].span(), commission, owner,
    );
    let randomSelector = create_stage(
        StageType::Randomness, owner, ZERO(), ZERO(), Option::None, [].span(), commission, owner,
    );
   
    let selector_classhash = get_class_hash(selector);
    let batch_selector_classhash = get_class_hash(batchSelector);
    let random_classhash = get_class_hash(randomSelector);

    let contract = declare("StageFactory").unwrap().contract_class();
    let mut constructor_calldata = array![];

    constructor_calldata.append_serde(owner);
    constructor_calldata.append_serde(commission);
    constructor_calldata.append_serde(selector_classhash);
    constructor_calldata.append_serde(batch_selector_classhash);
    constructor_calldata.append_serde(random_classhash);
    constructor_calldata.append_serde(owner); // fake vrf provider

    let (contract_address, _) = contract.deploy(@constructor_calldata).unwrap();
    let launpad_dispatcher = IStageFactoryDispatcher { contract_address };

    (contract_address, launpad_dispatcher)
}

// Value generated by script `create_merkle_tree`
const ROOT: felt252 = 0x055bd56277c7f6d8a43e368d693619129eabb968848688f93585911fee73154a;

const PROOF: [felt252; 2] = [
    0x03ab7a2f13b922344ed643f927acf82c486bab97a73fdbba9dbcddb735735cba,
    0x077787c98250e3bffdb3069d2893e2d9c7805ae48dfa687b1471c8fcaa1901d6,
];

fn setup_stage(
    id: u128,
    stageType: StageType,
    rootWhitelist: Option::<felt252>,
    collectionWhitelists: Span<ContractAddress>,
    commission: u32,
) -> (ContractAddress, ContractAddress, Stage, ContractAddress, ContractAddress, ContractAddress) {
    let owner = setup_account(SELLER1);
    let buyer = setup_account(BUYER1);

    let payment_address = create_erc20(buyer);
    let nft_address = create_oerc1155(owner);

    let (launchpad_address, launchpad_contract) = create_open_launchpad(owner, commission);

    let stage = Stage {
        stageType: StageType::BatchSelector,
        collection: nft_address,
        payment: payment_address,
        price: 10,
        maxAllocation: 10,
        limit: 6,
        startTime: 10,
        endTime: 100,
    };

    let id = 10;
    start_cheat_caller_address(launchpad_address, owner);
    launchpad_contract.createInstance(id, stage, rootWhitelist, collectionWhitelists);
    let stage_address = launchpad_contract.getInstance(id);

    start_cheat_block_timestamp(stage_address, 10);

    start_cheat_caller_address(payment_address, buyer);
    let payment_dispatcher = IERC20Dispatcher { contract_address: payment_address };
    payment_dispatcher.approve(stage_address, 100000000);
    stop_cheat_caller_address(payment_address);

    start_cheat_caller_address(nft_address, owner);
    let accesscontrol_dispatcher = IAccessControlDispatcher { contract_address: nft_address };
    accesscontrol_dispatcher.grant_role(MINTER_ROLE, stage_address);
    stop_cheat_caller_address(nft_address);

    return (owner, buyer, stage, stage_address, nft_address, payment_address);
}

#[test]
fn create_stage_works() {
    let owner = setup_account(SELLER1);

    let payment_address = setup_balance_at(toAddress(TEST_PAYMENT));
    let nft_address = do_setup_oerc721_at(toAddress(TEST_NFT), owner);

    let (launchpad_address, launchpad_contract) = create_open_launchpad(owner, 0);

    let stage = Stage {
        stageType: StageType::BatchSelector,
        collection: nft_address,
        payment: payment_address,
        price: 10,
        maxAllocation: 10,
        limit: 6,
        startTime: 10,
        endTime: 100,
    };

    let id = 10;
    start_cheat_caller_address(launchpad_address, owner);

    let mut spy = spy_events();
    launchpad_contract.createInstance(id, stage, Option::None, [].span());
    let stage_selector = launchpad_contract.getInstance(id);

    let expected_event = StageFactory::Event::StageCreated(
        StageCreated {
            stageId: id,
            owner,
            stageAddress: stage_selector,
            stage,
            rootWhitelist: Option::None,
            collectionWhitelists: [].span(),
        },
    );
    spy.assert_emitted(@array![(launchpad_address, expected_event)]);

    let ostage_dispatcher = IOStageDispatcher { contract_address: stage_selector };
    let stage_info = ostage_dispatcher.getInstance();

    assert(stage_info == stage, 'Get stage failed');
}

#[test]
fn buy_works() {
    let id = 10;
    let (_, buyer, stage, stage_address, nft_address, payment_address) = setup_stage(
        id, StageType::BatchSelector, Option::None, [].span(), 0,
    );

    let payment_dispatcher = IERC20Dispatcher { contract_address: payment_address };
    let nft_dispatcher = IERC1155Dispatcher { contract_address: nft_address };

    let buyer_before_balance = payment_dispatcher.balance_of(buyer);

    start_cheat_caller_address(stage_address, buyer);
    let stage_selector_dispatcher = IStageBatchSelectorDispatcher {
        contract_address: stage_address,
    };

    let mut spy = spy_events();
    stage_selector_dispatcher.buy([0, 1, 2].span(), [2, 2, 2].span(), [].span());
    let expected_event = StageBatchSelector::Event::TokensBought(
        TokensBought { buyer, amount: 6, paymentToken: payment_address, price: stage.price },
    );
    spy.assert_emitted(@array![(stage_address, expected_event)]);

    let amount = 6;
    let cost = amount * stage.price;
    let buyer_after_balance = payment_dispatcher.balance_of(buyer);

    // Verify balance
    assert(nft_dispatcher.balance_of(buyer, 0) == 2, 'NFT owner incorrect');
    assert(nft_dispatcher.balance_of(buyer, 1) == 2, 'NFT owner incorrect');
    assert(nft_dispatcher.balance_of(buyer, 2) == 2, 'NFT owner incorrect');

    assert(buyer_after_balance == buyer_before_balance - cost.into(), 'Buyer balance incoorect');

    // Verify states
    let provider = IOStageDispatcher { contract_address: stage_address };
    assert(provider.getMintedCount() == amount.into(), 'Minted count incorrect');
    assert(provider.getUserMintedCount(buyer) == amount.into(), 'User minted count incorrect');
}

#[test]
fn buy_with_root_whitelist_works() {
    let id = 10;
    let (_, buyer, stage, stage_address, nft_address, payment_address) = setup_stage(
        id, StageType::BatchSelector, Option::Some(ROOT), [].span(), 0,
    );

    let payment_dispatcher = IERC20Dispatcher { contract_address: payment_address };
    let nft_dispatcher = IERC1155Dispatcher { contract_address: nft_address };

    let buyer_before_balance = payment_dispatcher.balance_of(buyer);

    start_cheat_caller_address(stage_address, buyer);
    let stage_selector_dispatcher = IStageBatchSelectorDispatcher {
        contract_address: stage_address,
    };

    let mut spy = spy_events();
    stage_selector_dispatcher.buy([0, 1, 2].span(), [2, 2, 2].span(), PROOF.span());
    let expected_event = StageBatchSelector::Event::TokensBought(
        TokensBought { buyer, amount: 6, paymentToken: payment_address, price: stage.price },
    );
    spy.assert_emitted(@array![(stage_address, expected_event)]);

    let amount = 6;
    let cost = amount * stage.price;
    let buyer_after_balance = payment_dispatcher.balance_of(buyer);

    // Verify balance
    assert(nft_dispatcher.balance_of(buyer, 0) == 2, 'NFT owner incorrect');
    assert(nft_dispatcher.balance_of(buyer, 1) == 2, 'NFT owner incorrect');
    assert(nft_dispatcher.balance_of(buyer, 2) == 2, 'NFT owner incorrect');

    assert(buyer_after_balance == buyer_before_balance - cost.into(), 'Buyer balance incoorect');

    // Verify states
    let provider = IOStageDispatcher { contract_address: stage_address };
    assert(provider.getMintedCount() == amount.into(), 'Minted count incorrect');
    assert(provider.getUserMintedCount(buyer) == amount.into(), 'User minted count incorrect');
}

#[test]
fn buy_with_collection_whitelist_works() {
    let id = 10;
    let admin = toAddress(SELLER2);
    let collection_whitelist = create_oerc721(admin);

    let (_, buyer, stage, stage_address, nft_address, payment_address) = setup_stage(
        id, StageType::BatchSelector, Option::None, [collection_whitelist].span(), 0,
    );

    let OERC721 = IERC721MinterDispatcher { contract_address: collection_whitelist };
    start_cheat_caller_address(collection_whitelist, admin);
    OERC721.mint(buyer, 10);

    let payment_dispatcher = IERC20Dispatcher { contract_address: payment_address };
    let nft_dispatcher = IERC1155Dispatcher { contract_address: nft_address };

    let buyer_before_balance = payment_dispatcher.balance_of(buyer);

    start_cheat_caller_address(stage_address, buyer);
    let stage_selector_dispatcher = IStageBatchSelectorDispatcher {
        contract_address: stage_address,
    };

    let mut spy = spy_events();
    stage_selector_dispatcher.buy([0, 1, 2].span(), [2, 2, 2].span(), [].span());
    let expected_event = StageBatchSelector::Event::TokensBought(
        TokensBought { buyer, amount: 6, paymentToken: payment_address, price: stage.price },
    );
    spy.assert_emitted(@array![(stage_address, expected_event)]);

    let amount = 6;
    let cost = amount * stage.price;
    let buyer_after_balance = payment_dispatcher.balance_of(buyer);

    // Verify balance
    assert(nft_dispatcher.balance_of(buyer, 0) == 2, 'NFT owner incorrect');
    assert(nft_dispatcher.balance_of(buyer, 1) == 2, 'NFT owner incorrect');
    assert(nft_dispatcher.balance_of(buyer, 2) == 2, 'NFT owner incorrect');

    assert(buyer_after_balance == buyer_before_balance - cost.into(), 'Buyer balance incoorect');

    // Verify states
    let provider = IOStageDispatcher { contract_address: stage_address };
    assert(provider.getMintedCount() == amount.into(), 'Minted count incorrect');
    assert(provider.getUserMintedCount(buyer) == amount.into(), 'User minted count incorrect');
}

#[test]
#[should_panic(expected: ('OM: closed',))]
fn close_stages_works() {
    let id = 10;
    let (owner, buyer, _, stage_address, _, _) = setup_stage(
        id, StageType::BatchSelector, Option::Some(ROOT), [].span(), 0,
    );

    start_cheat_caller_address(stage_address, owner);
    let stage_selector_dispatcher = IStageBatchSelectorDispatcher {
        contract_address: stage_address,
    };

    let mut spy = spy_events();
    stage_selector_dispatcher.closeStage();

    let expected_event = StageComponent::Event::StageClosed(StageClosed { caller: owner });
    spy.assert_emitted(@array![(stage_address, expected_event)]);

    start_cheat_caller_address(stage_address, buyer);
    stage_selector_dispatcher.buy([0, 1, 2].span(), [2, 2, 2].span(), PROOF.span());
}

#[test]
fn withdraw_sales_works() {
    let id = 10;
    let commission = 500; // 5%
    let admin = toAddress(0x1);
    let (owner, buyer, stage, stage_address, _, payment_address) = setup_stage(
        id, StageType::BatchSelector, Option::None, [].span(), commission,
    );

    let payment_dispatcher = IERC20Dispatcher { contract_address: payment_address };
    start_cheat_caller_address(stage_address, buyer);
    let stage_selector_dispatcher = IStageBatchSelectorDispatcher {
        contract_address: stage_address,
    };
    stage_selector_dispatcher.buy([0, 1, 2].span(), [2, 2, 2].span(), array![].span());
    let sales = 6 * stage.price;
    let payout = sales - (sales * commission.into() / PERMYRIAD);
    let fee = sales - payout;
    let owner_balance = payment_dispatcher.balance_of(owner);
    let admin_balance = payment_dispatcher.balance_of(admin);

    let ownable_dispatcher = IOwnableDispatcher { contract_address: stage_address };
    start_cheat_caller_address(stage_address, owner);
    ownable_dispatcher.transfer_ownership(admin);

    start_cheat_caller_address(stage_address, admin);

    let mut spy = spy_events();
    stage_selector_dispatcher.withdrawSales();

    let expected_event = StageComponent::Event::SalesWithdrawn(
        SalesWithdrawn { owner: admin, tokenPayment: stage.payment, amount: payout },
    );
    spy.assert_emitted(@array![(stage_address, expected_event)]);

    assert(
        payment_dispatcher.balance_of(admin) == owner_balance + payout.into(),
        'seller balance incorrect',
    );
    assert(
        payment_dispatcher.balance_of(owner) == admin_balance + fee.into(),
        'seller balance incorrect',
    );
}

#[test]
#[should_panic(expected: ('OM: sold out',))]
fn buy_sold_out_panics() {
    let buyer1 = toAddress(BUYER1);
    let buyer2 = toAddress(BUYER2);

    let id = 10;
    let (_, _, _, stage_address, _, payment_address) = setup_stage(
        id, StageType::BatchSelector, Option::None, [].span(), 0,
    );

    let payment_dispatcher = IERC20Dispatcher { contract_address: payment_address };
    start_cheat_caller_address(payment_address, buyer1);
    payment_dispatcher.approve(stage_address, 1000000);
    stop_cheat_caller_address(payment_address);
    start_cheat_caller_address(stage_address, buyer1);
    let stage_selector_dispatcher = IStageBatchSelectorDispatcher {
        contract_address: stage_address,
    };
    stage_selector_dispatcher.buy([0, 1, 2].span(), [2, 2, 2].span(), array![].span());

    start_cheat_caller_address(payment_address, buyer2);
    payment_dispatcher.approve(stage_address, 1000000);
    stop_cheat_caller_address(payment_address);
    start_cheat_caller_address(stage_address, buyer2);
    let stage_selector_dispatcher = IStageBatchSelectorDispatcher {
        contract_address: stage_address,
    };
    stage_selector_dispatcher.buy([6, 7, 8].span(), [2, 2, 2].span(), array![].span());
}

#[test]
#[should_panic(expected: ('OM: exceed limit',))]
fn buy_exceed_limit_panics() {
    let id = 10;
    let (_, buyer, _, stage_address, _, _) = setup_stage(
        id, StageType::BatchSelector, Option::None, [].span(), 0,
    );

    start_cheat_caller_address(stage_address, buyer);
    let stage_selector_dispatcher = IStageBatchSelectorDispatcher {
        contract_address: stage_address,
    };
    stage_selector_dispatcher.buy([0, 1, 2, 3].span(), [2, 2, 2, 2].span(), array![].span());
}

#[test]
#[should_panic(expected: ('OM: root whitelist failed',))]
fn root_whitelist_failed_panics() {
    let id = 10;
    let (_, buyer, _, stage_address, _, _) = setup_stage(
        id, StageType::BatchSelector, Option::Some(ROOT), [].span(), 0,
    );

    start_cheat_caller_address(stage_address, buyer);
    let stage_selector_dispatcher = IStageBatchSelectorDispatcher {
        contract_address: stage_address,
    };
    stage_selector_dispatcher.buy([0, 1, 2].span(), [2, 2, 2].span(), array![].span());
}

#[test]
#[should_panic(expected: ('OM: collection whitelist failed',))]
fn collection_whitelist_failed_panics() {
    let id = 10;
    let collection_whitelist = create_oerc721(toAddress(SELLER2));
    let (_, buyer, _, stage_address, _, _) = setup_stage(
        id, StageType::BatchSelector, Option::None, [collection_whitelist].span(), 0,
    );

    start_cheat_caller_address(stage_address, buyer);
    let stage_selector_dispatcher = IStageBatchSelectorDispatcher {
        contract_address: stage_address,
    };
    stage_selector_dispatcher.buy([0, 1, 2].span(), [2, 2, 2].span(), array![].span());
}

#[test]
#[should_panic(expected: ('OM: stage not started',))]
fn buy_stage_not_started_panics() {
    let id = 10;
    let (_, buyer, stage, stage_address, _, _) = setup_stage(
        id, StageType::BatchSelector, Option::None, [].span(), 0,
    );

    start_cheat_caller_address(stage_address, buyer);
    let stage_selector_dispatcher = IStageBatchSelectorDispatcher {
        contract_address: stage_address,
    };
    start_cheat_block_timestamp(stage_address, (stage.startTime - 1).try_into().unwrap());

    start_cheat_caller_address(stage_address, buyer);
    stage_selector_dispatcher.buy([0, 1, 2].span(), [2, 2, 2].span(), array![].span());
}
#[test]
#[should_panic(expected: ('OM: stage has ended',))]
fn buy_stage_ended_panics() {
    let id = 10;
    let (_, buyer, stage, stage_address, _, _) = setup_stage(
        id, StageType::BatchSelector, Option::None, [].span(), 0,
    );

    start_cheat_caller_address(stage_address, buyer);
    let stage_selector_dispatcher = IStageBatchSelectorDispatcher {
        contract_address: stage_address,
    };
    start_cheat_block_timestamp(stage_address, (stage.endTime + 1).try_into().unwrap());

    start_cheat_caller_address(stage_address, buyer);
    stage_selector_dispatcher.buy([0, 1, 2].span(), [2, 2, 2].span(), array![].span());
}

#[test]
#[should_panic(expected: ('OM: ID in use',))]
fn update_stages_id_used_panics() {
    let owner = toAddress(SELLER1);
    let buyer = toAddress(BUYER1);

    let payment_address = create_erc20(buyer);
    let nft_address = create_oerc1155(owner);

    let (launchpad_address, launchpad_contract) = create_open_launchpad(owner, 0);

    let stage = Stage {
        stageType: StageType::BatchSelector,
        collection: nft_address,
        payment: payment_address,
        price: 10,
        maxAllocation: 10,
        limit: 6,
        startTime: 10,
        endTime: 100,
    };

    let id = 10;
    start_cheat_caller_address(launchpad_address, owner);
    launchpad_contract.createInstance(id, stage, Option::None, [].span());
    launchpad_contract.createInstance(id, stage, Option::None, [].span());
}

#[test]
#[should_panic(expected: ('Caller is not the owner',))]
fn clost_stage_not_owner_panics() {
    let not_owner = toAddress(0x1);
    let id = 10;
    let (_, buyer, stage, stage_address, _, _) = setup_stage(
        id, StageType::BatchSelector, Option::None, [].span(), 0,
    );

    start_cheat_caller_address(stage_address, buyer);
    let stage_dispatcher = IStageBatchSelectorDispatcher { contract_address: stage_address };
    start_cheat_block_timestamp(stage_address, (stage.endTime + 1).try_into().unwrap());

    start_cheat_caller_address(stage_address, not_owner);
    stage_dispatcher.closeStage();
}

#[test]
#[should_panic(expected: ('Caller is not the owner',))]
fn withdraw_sales_not_owner_panics() {
    let not_owner = toAddress(0x1);
    let id = 10;
    let (_, buyer, stage, stage_address, _, _) = setup_stage(
        id, StageType::BatchSelector, Option::None, [].span(), 0,
    );

    start_cheat_caller_address(stage_address, buyer);
    let stage_dispatcher = IStageBatchSelectorDispatcher { contract_address: stage_address };
    start_cheat_block_timestamp(stage_address, (stage.endTime + 1).try_into().unwrap());

    start_cheat_caller_address(stage_address, not_owner);
    stage_dispatcher.withdrawSales();
}

