use snforge_std::EventSpyAssertionsTrait;
use openzeppelin::utils::serde::SerializedAppend;
use openzeppelin::token::erc20::interface::{IERC20Dispatcher, IERC20DispatcherTrait};
use openzeppelin::token::erc1155::interface::{IERC1155Dispatcher, IERC1155DispatcherTrait};
use openzeppelin::access::accesscontrol::interface::{
    IAccessControlDispatcher, IAccessControlDispatcherTrait,
};
use openzeppelin::access::ownable::interface::{IOwnableDispatcher, IOwnableDispatcherTrait};

use snforge_std::{
    declare, ContractClassTrait, start_cheat_caller_address, stop_cheat_caller_address,
    start_cheat_block_timestamp, DeclareResultTrait, get_class_hash, spy_events,
};
use starknet::{ContractAddress};
use openmark::tests::unit::common::{
    SELLER1, SELLER2, BUYER1, BUYER2, TEST_PAYMENT, TEST_NFT, toAddress, setup_balance_at,
    do_setup_oerc721_at, create_stage, create_oerc1155, create_erc20, setup_account, create_oerc721,
    ZERO,
};
use openmark::primitives::types::{Stage, StageType};
use openmark::primitives::constants::{MINTER_ROLE, PERMYRIAD};
use openmark::launchpad::interface::{
    IOStageDispatcher, IOStageDispatcherTrait, Source,
};
use openmark::assets::interface::{IERC721MinterDispatcher, IERC721MinterDispatcherTrait};
use openmark::factory::stage_factory::StageFactory;
use openmark::launchpad::stage::StageComponent;
use openmark::launchpad::interface::{
    IStageVRFDispatcher, IStageVRFDispatcherTrait, IVrfProviderDispatcher,
    IVrfProviderDispatcherTrait,
};
use openmark::factory::stage_factory::StageFactory::StageCreated;
use openmark::launchpad::events::{TokensBought, StageClosed, SalesWithdrawn};
use openmark::launchpad::stage_batch_selector::StageBatchSelector;
use openmark::factory::interface::{IStageFactoryDispatcher, IStageFactoryDispatcherTrait};
use openmark::primitives::types::DropEntry;

fn deploy_mock_vrf() -> ContractAddress {
    let contract = declare("VRFProviderMock").unwrap().contract_class();
    let (contract_address, _) = contract.deploy(@array![]).unwrap();
    contract_address
}

fn create_open_launchpad(
    owner: ContractAddress, commission: u32,
) -> (ContractAddress, IStageFactoryDispatcher) {
    let selector = create_stage(
        StageType::BatchSelector, owner, ZERO(), ZERO(), Option::None, [].span(), commission, owner,
    );
    let batchSelector = create_stage(
        StageType::BatchSelector, owner, ZERO(), ZERO(), Option::None, [].span(), commission, owner,
    );
    let randomSelector = create_stage(
        StageType::Randomness, owner, ZERO(), ZERO(), Option::None, [].span(), commission, owner,
    );

    let selector_classhash = get_class_hash(selector);
    let batch_selector_classhash = get_class_hash(batchSelector);
    let random_classhash = get_class_hash(randomSelector);
    let vrf_provider = deploy_mock_vrf();

    let contract = declare("StageFactory").unwrap().contract_class();
    let mut constructor_calldata = array![];

    constructor_calldata.append_serde(owner);
    constructor_calldata.append_serde(commission);
    constructor_calldata.append_serde(selector_classhash);
    constructor_calldata.append_serde(batch_selector_classhash);
    constructor_calldata.append_serde(random_classhash);
    constructor_calldata.append_serde(vrf_provider);

    let (contract_address, _) = contract.deploy(@constructor_calldata).unwrap();
    let launchpad_dispatcher = IStageFactoryDispatcher { contract_address };

    (contract_address, launchpad_dispatcher)
}

// Value generated by script `create_merkle_tree`
const ROOT: felt252 = 0x055bd56277c7f6d8a43e368d693619129eabb968848688f93585911fee73154a;

const PROOF: [felt252; 2] = [
    0x03ab7a2f13b922344ed643f927acf82c486bab97a73fdbba9dbcddb735735cba,
    0x077787c98250e3bffdb3069d2893e2d9c7805ae48dfa687b1471c8fcaa1901d6,
];

fn setup_stage(
    id: u128,
    stageType: StageType,
    rootWhitelist: Option::<felt252>,
    collectionWhitelists: Span<ContractAddress>,
    commission: u32,
) -> (ContractAddress, ContractAddress, Stage, ContractAddress, ContractAddress, ContractAddress) {
    let owner = setup_account(SELLER1);
    let buyer = setup_account(BUYER1);

    let payment_address = create_erc20(buyer);
    let nft_address = create_oerc1155(owner);

    let (launchpad_address, launchpad_contract) = create_open_launchpad(owner, commission);

    let stage = Stage {
        stageType: StageType::Randomness,
        collection: nft_address,
        payment: payment_address,
        price: 10,
        maxAllocation: 10,
        limit: 6,
        startTime: 10,
        endTime: 100,
    };

    start_cheat_caller_address(launchpad_address, owner);
    launchpad_contract.createInstance(id, stage, rootWhitelist, collectionWhitelists);
    let stage_address = launchpad_contract.getInstance(id);

    start_cheat_block_timestamp(stage_address, 10);

    start_cheat_caller_address(payment_address, buyer);
    let payment_dispatcher = IERC20Dispatcher { contract_address: payment_address };
    payment_dispatcher.approve(stage_address, 100000000);
    stop_cheat_caller_address(payment_address);

    let drop_table = array![
        DropEntry { token_id: 1, weight: 50 }, // 0-49
        DropEntry { token_id: 2, weight: 30 }, // 50-79
        DropEntry { token_id: 3, weight: 20 } // 80-99
    ]
        .span(); // total_weight = 100
    start_cheat_caller_address(stage_address, owner);
    let stage_dispatcher = IStageVRFDispatcher { contract_address: stage_address };
    stage_dispatcher.setup(drop_table);
    stop_cheat_caller_address(stage_address);

    start_cheat_caller_address(nft_address, owner);
    let accesscontrol_dispatcher = IAccessControlDispatcher { contract_address: nft_address };
    accesscontrol_dispatcher.grant_role(MINTER_ROLE, stage_address);
    stop_cheat_caller_address(nft_address);

    (owner, buyer, stage, stage_address, nft_address, payment_address)
}

#[test]
fn create_stage_works() {
    let owner = setup_account(SELLER1);

    let payment_address = setup_balance_at(toAddress(TEST_PAYMENT));
    let nft_address = do_setup_oerc721_at(toAddress(TEST_NFT), owner);

    let (launchpad_address, launchpad_contract) = create_open_launchpad(owner, 0);

    let stage = Stage {
        stageType: StageType::Randomness,
        collection: nft_address,
        payment: payment_address,
        price: 10,
        maxAllocation: 10,
        limit: 6,
        startTime: 10,
        endTime: 100,
    };

    let id = 10;
    start_cheat_caller_address(launchpad_address, owner);

    let mut spy = spy_events();
    launchpad_contract.createInstance(id, stage, Option::None, [].span());
    let stage_selector = launchpad_contract.getInstance(id);

    let expected_event = StageFactory::Event::StageCreated(
        StageCreated {
            stageId: id,
            owner,
            stageAddress: stage_selector,
            stage,
            rootWhitelist: Option::None,
            collectionWhitelists: [].span(),
        },
    );
    spy.assert_emitted(@array![(launchpad_address, expected_event)]);

    let ostage_dispatcher = IOStageDispatcher { contract_address: stage_selector };
    let stage_info = ostage_dispatcher.getInstance();

    assert(stage_info == stage, 'Get stage failed');
}

#[test]
fn buy_works() {
    let id = 10;
    let mintAmount = 5;
    let (_, buyer, stage, stage_address, nft_address, payment_address) = setup_stage(
        id, StageType::Randomness, Option::None, [].span(), 0,
    );

    let payment_dispatcher = IERC20Dispatcher { contract_address: payment_address };
    let nft_dispatcher = IERC1155Dispatcher { contract_address: nft_address };
    let stage_dispatcher = IStageVRFDispatcher { contract_address: stage_address };
    let vrf_provider = IVrfProviderDispatcher {
        contract_address: stage_dispatcher.get_vrf_provider(),
    };

    let buyer_before_balance = payment_dispatcher.balance_of(buyer);

    start_cheat_caller_address(vrf_provider.contract_address, buyer);
    vrf_provider.request_random(stage_dispatcher.contract_address, Source::Nonce(buyer));
    stop_cheat_caller_address(vrf_provider.contract_address);

    start_cheat_caller_address(stage_address, buyer);

    let mut spy = spy_events();
    stage_dispatcher.buy(mintAmount, [].span());
    let expected_event = StageBatchSelector::Event::TokensBought(
        TokensBought {
            buyer, amount: mintAmount, paymentToken: payment_address, price: stage.price,
        },
    );
    spy.assert_emitted(@array![(stage_address, expected_event)]);

    let cost = mintAmount * stage.price;
    let buyer_after_balance = payment_dispatcher.balance_of(buyer);

    // Verify balance
    let nft_balance = nft_dispatcher.balance_of(buyer, 1)
        + nft_dispatcher.balance_of(buyer, 2)
        + nft_dispatcher.balance_of(buyer, 3);
    assert(nft_balance == mintAmount, 'Buyer nft balance incorrect');

    assert(buyer_after_balance == buyer_before_balance - cost.into(), 'Buyer balance incorrect');

    // Verify states
    let provider = IOStageDispatcher { contract_address: stage_address };
    assert(provider.getMintedCount() == mintAmount.into(), 'Minted count incorrect');
    assert(provider.getUserMintedCount(buyer) == mintAmount.into(), 'User minted count incorrect');
}

#[test]
fn buy_with_root_whitelist_works() {
    let id = 10;
    let mintAmount = 3;
    let (_, buyer, stage, stage_address, nft_address, payment_address) = setup_stage(
        id, StageType::Randomness, Option::Some(ROOT), [].span(), 0,
    );

    let payment_dispatcher = IERC20Dispatcher { contract_address: payment_address };
    let nft_dispatcher = IERC1155Dispatcher { contract_address: nft_address };
    let stage_dispatcher = IStageVRFDispatcher { contract_address: stage_address };
    let vrf_provider = IVrfProviderDispatcher {
        contract_address: stage_dispatcher.get_vrf_provider(),
    };

    let buyer_before_balance = payment_dispatcher.balance_of(buyer);

    start_cheat_caller_address(vrf_provider.contract_address, buyer);
    vrf_provider.request_random(stage_dispatcher.contract_address, Source::Nonce(buyer));
    stop_cheat_caller_address(vrf_provider.contract_address);

    start_cheat_caller_address(stage_address, buyer);

    let mut spy = spy_events();
    stage_dispatcher.buy(mintAmount, PROOF.span());
    let expected_event = StageBatchSelector::Event::TokensBought(
        TokensBought {
            buyer, amount: mintAmount, paymentToken: payment_address, price: stage.price,
        },
    );
    spy.assert_emitted(@array![(stage_address, expected_event)]);

    let cost = mintAmount * stage.price;
    let buyer_after_balance = payment_dispatcher.balance_of(buyer);

    // Verify balance
    let nft_balance = nft_dispatcher.balance_of(buyer, 1)
        + nft_dispatcher.balance_of(buyer, 2)
        + nft_dispatcher.balance_of(buyer, 3);
    assert(nft_balance == mintAmount, 'Buyer nft balance incorrect');

    assert(buyer_after_balance == buyer_before_balance - cost.into(), 'Buyer balance incorrect');

    // Verify states
    let provider = IOStageDispatcher { contract_address: stage_address };
    assert(provider.getMintedCount() == mintAmount.into(), 'Minted count incorrect');
    assert(provider.getUserMintedCount(buyer) == mintAmount.into(), 'User minted count incorrect');
}

#[test]
fn buy_with_collection_whitelist_works() {
    let id = 10;
    let mintAmount = 3;
    let admin = setup_account(SELLER2);
    let collection_whitelist = create_oerc721(admin);

    let (_, buyer, stage, stage_address, nft_address, payment_address) = setup_stage(
        id, StageType::Randomness, Option::None, [collection_whitelist].span(), 0,
    );

    let oerc721 = IERC721MinterDispatcher { contract_address: collection_whitelist };
    start_cheat_caller_address(collection_whitelist, admin);
    oerc721.mint(buyer, 10);
    stop_cheat_caller_address(collection_whitelist);

    let payment_dispatcher = IERC20Dispatcher { contract_address: payment_address };
    let nft_dispatcher = IERC1155Dispatcher { contract_address: nft_address };
    let stage_dispatcher = IStageVRFDispatcher { contract_address: stage_address };
    let vrf_provider = IVrfProviderDispatcher {
        contract_address: stage_dispatcher.get_vrf_provider(),
    };

    let buyer_before_balance = payment_dispatcher.balance_of(buyer);

    start_cheat_caller_address(vrf_provider.contract_address, buyer);
    vrf_provider.request_random(stage_dispatcher.contract_address, Source::Nonce(buyer));
    stop_cheat_caller_address(vrf_provider.contract_address);

    start_cheat_caller_address(stage_address, buyer);

    let mut spy = spy_events();
    stage_dispatcher.buy(mintAmount, [].span());
    let expected_event = StageBatchSelector::Event::TokensBought(
        TokensBought {
            buyer, amount: mintAmount, paymentToken: payment_address, price: stage.price,
        },
    );
    spy.assert_emitted(@array![(stage_address, expected_event)]);

    let cost = mintAmount * stage.price;
    let buyer_after_balance = payment_dispatcher.balance_of(buyer);

    // Verify balance
    let nft_balance = nft_dispatcher.balance_of(buyer, 1)
        + nft_dispatcher.balance_of(buyer, 2)
        + nft_dispatcher.balance_of(buyer, 3);
    assert(nft_balance == mintAmount, 'Buyer nft balance incorrect');

    assert(buyer_after_balance == buyer_before_balance - cost.into(), 'Buyer balance incorrect');

    // Verify states
    let provider = IOStageDispatcher { contract_address: stage_address };
    assert(provider.getMintedCount() == mintAmount.into(), 'Minted count incorrect');
    assert(provider.getUserMintedCount(buyer) == mintAmount.into(), 'User minted count incorrect');
}

#[test]
#[should_panic(expected: ('OM: closed',))]
fn close_stages_works() {
    let id = 10;
    let mintAmount = 3;
    let (owner, buyer, _, stage_address, _, _) = setup_stage(
        id, StageType::Randomness, Option::Some(ROOT), [].span(), 0,
    );

    let stage_dispatcher = IStageVRFDispatcher { contract_address: stage_address };
    let vrf_provider = IVrfProviderDispatcher {
        contract_address: stage_dispatcher.get_vrf_provider(),
    };

    start_cheat_caller_address(stage_address, owner);
    let mut spy = spy_events();
    stage_dispatcher.closeStage();

    let expected_event = StageComponent::Event::StageClosed(StageClosed { caller: owner });
    spy.assert_emitted(@array![(stage_address, expected_event)]);

    start_cheat_caller_address(vrf_provider.contract_address, buyer);
    vrf_provider.request_random(stage_dispatcher.contract_address, Source::Nonce(buyer));
    stop_cheat_caller_address(vrf_provider.contract_address);

    start_cheat_caller_address(stage_address, buyer);
    stage_dispatcher.buy(mintAmount, PROOF.span());
}

#[test]
fn withdraw_sales_works() {
    let id = 10;
    let commission = 500; // 5%
    let admin = setup_account(0x1);
    let mintAmount = 3;
    let (owner, buyer, stage, stage_address, _, payment_address) = setup_stage(
        id, StageType::Randomness, Option::None, [].span(), commission,
    );

    let payment_dispatcher = IERC20Dispatcher { contract_address: payment_address };
    let stage_dispatcher = IStageVRFDispatcher { contract_address: stage_address };
    let vrf_provider = IVrfProviderDispatcher {
        contract_address: stage_dispatcher.get_vrf_provider(),
    };

    start_cheat_caller_address(vrf_provider.contract_address, buyer);
    vrf_provider.request_random(stage_dispatcher.contract_address, Source::Nonce(buyer));
    stop_cheat_caller_address(vrf_provider.contract_address);

    start_cheat_caller_address(stage_address, buyer);
    stage_dispatcher.buy(mintAmount, [].span());
    stop_cheat_caller_address(stage_address);

    let sales = mintAmount * stage.price;
    let payout = sales - (sales * commission.into() / PERMYRIAD);
    let fee = sales - payout;
    let owner_balance = payment_dispatcher.balance_of(owner);
    let admin_balance = payment_dispatcher.balance_of(admin);

    let ownable_dispatcher = IOwnableDispatcher { contract_address: stage_address };
    start_cheat_caller_address(stage_address, owner);
    ownable_dispatcher.transfer_ownership(admin);
    stop_cheat_caller_address(stage_address);

    start_cheat_caller_address(stage_address, admin);
    let mut spy = spy_events();
    stage_dispatcher.withdrawSales();

    let expected_event = StageComponent::Event::SalesWithdrawn(
        SalesWithdrawn { owner: admin, tokenPayment: stage.payment, amount: payout },
    );
    spy.assert_emitted(@array![(stage_address, expected_event)]);

    assert(
        payment_dispatcher.balance_of(admin) == owner_balance + payout.into(),
        'seller balance incorrect',
    );
    assert(
        payment_dispatcher.balance_of(owner) == admin_balance + fee.into(),
        'seller balance incorrect',
    );
}

#[test]
#[should_panic(expected: ('OM: sold out',))]
fn buy_sold_out_panics() {
    let id = 10;
    let buyer2 = setup_account(BUYER2);

    let (_, buyer1, _, stage_address, _, payment_address) = setup_stage(
        id, StageType::Randomness, Option::None, [].span(), 0,
    );

    let payment_dispatcher = IERC20Dispatcher { contract_address: payment_address };
    let stage_dispatcher = IStageVRFDispatcher { contract_address: stage_address };
    let vrf_provider = IVrfProviderDispatcher {
        contract_address: stage_dispatcher.get_vrf_provider(),
    };

    start_cheat_caller_address(payment_address, buyer1);
    payment_dispatcher.approve(stage_address, 1000000);
    stop_cheat_caller_address(payment_address);

    start_cheat_caller_address(vrf_provider.contract_address, buyer1);
    vrf_provider.request_random(stage_dispatcher.contract_address, Source::Nonce(buyer1));
    stop_cheat_caller_address(vrf_provider.contract_address);

    start_cheat_caller_address(stage_address, buyer1);
    stage_dispatcher.buy(6, [].span());
    stop_cheat_caller_address(stage_address);

    start_cheat_caller_address(payment_address, buyer2);
    payment_dispatcher.approve(stage_address, 1000000);
    stop_cheat_caller_address(payment_address);

    start_cheat_caller_address(vrf_provider.contract_address, buyer2);
    vrf_provider.request_random(stage_dispatcher.contract_address, Source::Nonce(buyer2));
    stop_cheat_caller_address(vrf_provider.contract_address);

    start_cheat_caller_address(stage_address, buyer2);
    stage_dispatcher.buy(5, [].span()); // Exceeds maxAllocation (10)
}

#[test]
#[should_panic(expected: ('OM: exceed limit',))]
fn buy_exceed_limit_panics() {
    let id = 10;
    let (_, buyer, _, stage_address, _, _) = setup_stage(
        id, StageType::Randomness, Option::None, [].span(), 0,
    );

    let stage_dispatcher = IStageVRFDispatcher { contract_address: stage_address };
    let vrf_provider = IVrfProviderDispatcher {
        contract_address: stage_dispatcher.get_vrf_provider(),
    };

    start_cheat_caller_address(vrf_provider.contract_address, buyer);
    vrf_provider.request_random(stage_dispatcher.contract_address, Source::Nonce(buyer));
    stop_cheat_caller_address(vrf_provider.contract_address);

    start_cheat_caller_address(stage_address, buyer);
    stage_dispatcher.buy(7, [].span()); // Exceeds limit (6)
}

#[test]
#[should_panic(expected: ('OM: root whitelist failed',))]
fn root_whitelist_failed_panics() {
    let id = 10;
    let mintAmount = 3;
    let (_, buyer, _, stage_address, _, _) = setup_stage(
        id, StageType::Randomness, Option::Some(ROOT), [].span(), 0,
    );

    let stage_dispatcher = IStageVRFDispatcher { contract_address: stage_address };
    let vrf_provider = IVrfProviderDispatcher {
        contract_address: stage_dispatcher.get_vrf_provider(),
    };

    start_cheat_caller_address(vrf_provider.contract_address, buyer);
    vrf_provider.request_random(stage_dispatcher.contract_address, Source::Nonce(buyer));
    stop_cheat_caller_address(vrf_provider.contract_address);

    start_cheat_caller_address(stage_address, buyer);
    stage_dispatcher.buy(mintAmount, [].span()); // No proof provided, should fail
}

#[test]
#[should_panic(expected: ('OM: collection whitelist failed',))]
fn collection_whitelist_failed_panics() {
    let id = 10;
    let mintAmount = 3;
    let collection_whitelist = create_oerc721(setup_account(SELLER2));
    let (_, buyer, _, stage_address, _, _) = setup_stage(
        id, StageType::Randomness, Option::None, [collection_whitelist].span(), 0,
    );

    let stage_dispatcher = IStageVRFDispatcher { contract_address: stage_address };
    let vrf_provider = IVrfProviderDispatcher {
        contract_address: stage_dispatcher.get_vrf_provider(),
    };

    start_cheat_caller_address(vrf_provider.contract_address, buyer);
    vrf_provider.request_random(stage_dispatcher.contract_address, Source::Nonce(buyer));
    stop_cheat_caller_address(vrf_provider.contract_address);

    start_cheat_caller_address(stage_address, buyer);
    stage_dispatcher.buy(mintAmount, [].span()); // Buyer doesn’t own whitelist NFT
}

#[test]
#[should_panic(expected: ('OM: stage not started',))]
fn buy_stage_not_started_panics() {
    let id = 10;
    let mintAmount = 3;
    let (_, buyer, stage, stage_address, _, _) = setup_stage(
        id, StageType::Randomness, Option::None, [].span(), 0,
    );

    let stage_dispatcher = IStageVRFDispatcher { contract_address: stage_address };
    let vrf_provider = IVrfProviderDispatcher {
        contract_address: stage_dispatcher.get_vrf_provider(),
    };

    start_cheat_block_timestamp(stage_address, (stage.startTime - 1).try_into().unwrap());

    start_cheat_caller_address(vrf_provider.contract_address, buyer);
    vrf_provider.request_random(stage_dispatcher.contract_address, Source::Nonce(buyer));
    stop_cheat_caller_address(vrf_provider.contract_address);

    start_cheat_caller_address(stage_address, buyer);
    stage_dispatcher.buy(mintAmount, [].span());
}

#[test]
#[should_panic(expected: ('OM: stage has ended',))]
fn buy_stage_ended_panics() {
    let id = 10;
    let mintAmount = 3;
    let (_, buyer, stage, stage_address, _, _) = setup_stage(
        id, StageType::Randomness, Option::None, [].span(), 0,
    );

    let stage_dispatcher = IStageVRFDispatcher { contract_address: stage_address };
    let vrf_provider = IVrfProviderDispatcher {
        contract_address: stage_dispatcher.get_vrf_provider(),
    };

    start_cheat_block_timestamp(stage_address, (stage.endTime + 1).try_into().unwrap());

    start_cheat_caller_address(vrf_provider.contract_address, buyer);
    vrf_provider.request_random(stage_dispatcher.contract_address, Source::Nonce(buyer));
    stop_cheat_caller_address(vrf_provider.contract_address);

    start_cheat_caller_address(stage_address, buyer);
    stage_dispatcher.buy(mintAmount, [].span());
}

#[test]
#[should_panic(expected: ('OM: ID in use',))]
fn update_stages_id_used_panics() {
    let owner = setup_account(SELLER1);
    let buyer = setup_account(BUYER1);

    let payment_address = create_erc20(buyer);
    let nft_address = create_oerc1155(owner);

    let (launchpad_address, launchpad_contract) = create_open_launchpad(owner, 0);

    let stage = Stage {
        stageType: StageType::Randomness,
        collection: nft_address,
        payment: payment_address,
        price: 10,
        maxAllocation: 10,
        limit: 6,
        startTime: 10,
        endTime: 100,
    };

    let id = 10;
    start_cheat_caller_address(launchpad_address, owner);
    launchpad_contract.createInstance(id, stage, Option::None, [].span());
    launchpad_contract.createInstance(id, stage, Option::None, [].span());
}

#[test]
#[should_panic(expected: ('Caller is not the owner',))]
fn close_stage_not_owner_panics() {
    let id = 10;
    let mintAmount = 3;
    let not_owner = setup_account(0x1);
    let (_, buyer, stage, stage_address, _, _) = setup_stage(
        id, StageType::Randomness, Option::None, [].span(), 0,
    );

    let stage_dispatcher = IStageVRFDispatcher { contract_address: stage_address };
    let vrf_provider = IVrfProviderDispatcher {
        contract_address: stage_dispatcher.get_vrf_provider(),
    };

    start_cheat_block_timestamp(stage_address, (stage.endTime + 1).try_into().unwrap());

    start_cheat_caller_address(vrf_provider.contract_address, buyer);
    vrf_provider.request_random(stage_dispatcher.contract_address, Source::Nonce(buyer));
    stop_cheat_caller_address(vrf_provider.contract_address);

    start_cheat_caller_address(stage_address, not_owner);
    stage_dispatcher.closeStage();
}

#[test]
#[should_panic(expected: ('Caller is not the owner',))]
fn withdraw_sales_not_owner_panics() {
    let id = 10;
    let mintAmount = 3;
    let not_owner = setup_account(0x1);
    let (_, buyer, stage, stage_address, _, _) = setup_stage(
        id, StageType::Randomness, Option::None, [].span(), 0,
    );

    let stage_dispatcher = IStageVRFDispatcher { contract_address: stage_address };
    let vrf_provider = IVrfProviderDispatcher {
        contract_address: stage_dispatcher.get_vrf_provider(),
    };

    start_cheat_block_timestamp(stage_address, (stage.endTime + 1).try_into().unwrap());

    start_cheat_caller_address(vrf_provider.contract_address, buyer);
    vrf_provider.request_random(stage_dispatcher.contract_address, Source::Nonce(buyer));
    stop_cheat_caller_address(vrf_provider.contract_address);

    start_cheat_caller_address(stage_address, not_owner);
    stage_dispatcher.withdrawSales();
}

#[test]
#[should_panic(expected: ('OM: Drop table not initialized',))]
fn buy_drop_table_not_initialized_panics() {
    let id = 10;
    let mintAmount = 3;
    let owner = setup_account(SELLER1);
    let buyer = setup_account(BUYER1);

    let payment_address = create_erc20(buyer);
    let nft_address = create_oerc1155(owner);
    let (launchpad_address, launchpad_contract) = create_open_launchpad(owner, 0);

    let stage = Stage {
        stageType: StageType::Randomness,
        collection: nft_address,
        payment: payment_address,
        price: 10,
        maxAllocation: 10,
        limit: 6,
        startTime: 10,
        endTime: 100,
    };

    start_cheat_caller_address(launchpad_address, owner);
    launchpad_contract.createInstance(id, stage, Option::None, [].span());
    let stage_address = launchpad_contract.getInstance(id);
    stop_cheat_caller_address(launchpad_address);

    start_cheat_block_timestamp(stage_address, 10);

    start_cheat_caller_address(payment_address, buyer);
    let payment_dispatcher = IERC20Dispatcher { contract_address: payment_address };
    payment_dispatcher.approve(stage_address, 100000000);
    stop_cheat_caller_address(payment_address);

    start_cheat_caller_address(nft_address, owner);
    let accesscontrol_dispatcher = IAccessControlDispatcher { contract_address: nft_address };
    accesscontrol_dispatcher.grant_role(MINTER_ROLE, stage_address);
    stop_cheat_caller_address(nft_address);

    let stage_dispatcher = IStageVRFDispatcher { contract_address: stage_address };
    let vrf_provider = IVrfProviderDispatcher { contract_address: stage_dispatcher.get_vrf_provider() };

    start_cheat_caller_address(vrf_provider.contract_address, buyer);
    vrf_provider.request_random(stage_dispatcher.contract_address, Source::Nonce(buyer));
    stop_cheat_caller_address(vrf_provider.contract_address);

    start_cheat_caller_address(stage_address, buyer);
    stage_dispatcher.buy(mintAmount, [].span());
}